/**
 * systemd --user unit for the MBA daemon (`mba start` / `mba stop` / `mba restart`).
 *
 * Same supervisor as a hand-rolled `~/.config/systemd/user/mba.service`:
 * Type=simple, Restart=on-failure. Generated so ExecStart is this install's
 * node + daemon entry, not a hardcoded checkout. Machine env (CUDA, ROCm)
 * lives in `mba.service.d/local.conf` and is not overwritten.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

export const UNIT_NAME = "mba.service";
export const UNIT_MARKER = "# Generated by mba start.";

export function userSystemdDir(home: string = homedir(), env: NodeJS.ProcessEnv = process.env): string {
  const xdg = env.XDG_CONFIG_HOME;
  const config = xdg && xdg.length > 0 ? xdg : join(home, ".config");
  return join(config, "systemd", "user");
}

export function unitPath(home?: string, env?: NodeJS.ProcessEnv): string {
  return join(userSystemdDir(home, env), UNIT_NAME);
}

export function localDropInPath(home?: string, env?: NodeJS.ProcessEnv): string {
  return join(userSystemdDir(home, env), "mba.service.d", "local.conf");
}

export function systemdQuote(value: string): string {
  if (value.length > 0 && !/[\s"'\\]/.test(value)) return value;
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function extraEnvironmentLines(unitText: string): string[] {
  const extra: string[] = [];
  for (const line of unitText.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("Environment=")) continue;
    const body = trimmed.slice("Environment=".length);
    const key = body.split("=")[0] ?? "";
    if (key === "PATH" || key.length === 0) continue;
    extra.push(`Environment=${body}`);
  }
  return extra;
}

export function renderLocalDropIn(envLines: readonly string[]): string {
  return [
    "# Local machine env for mba.service. `mba start` does not overwrite this file.",
    "[Service]",
    ...envLines,
    "",
  ].join("\n");
}

export function renderMbaUserUnit(opts: { execStart: string; pathEnv: string }): string {
  return [
    UNIT_MARKER,
    "# Machine env: mba.service.d/local.conf",
    "[Unit]",
    "Description=MBA daemon",
    "After=network.target",
    "",
    "[Service]",
    "Type=simple",
    `ExecStart=${opts.execStart}`,
    "Restart=on-failure",
    "RestartSec=3",
    `Environment=PATH=${systemdQuote(opts.pathEnv)}`,
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
}

export function resolveDaemonArgv(): { argv: string[]; pathEnv: string } {
  const js = fileURLToPath(new URL("../service/main.js", import.meta.url));
  const ts = js.replace(/\.js$/, ".ts");
  const main = existsSync(js) ? js : ts;
  const nodeDir = dirname(process.execPath);
  const pathEnv = `${nodeDir}:/usr/local/bin:/usr/bin:/bin`;

  if (main.endsWith(".ts")) {
    const tsx = resolveTsxCli();
    if (!tsx) {
      throw new Error("mba start from source needs tsx, or build @mba-ai/core first");
    }
    return { argv: [process.execPath, tsx, main], pathEnv };
  }
  return { argv: [process.execPath, main], pathEnv };
}

function resolveTsxCli(): string | null {
  try {
    const require = createRequire(import.meta.url);
    const pkg = dirname(require.resolve("tsx/package.json"));
    const cli = join(pkg, "dist", "cli.mjs");
    return existsSync(cli) ? cli : null;
  } catch {
    return null;
  }
}

export function execStartLine(argv: readonly string[]): string {
  return argv.map(systemdQuote).join(" ");
}

export function hasUserSystemd(): boolean {
  if (process.platform !== "linux") return false;
  try {
    const r = spawnSync("systemctl", ["--user", "show-environment"], {
      encoding: "utf8",
      timeout: 4000,
    });
    return r.status === 0;
  } catch {
    return false;
  }
}

function userSystemctl(args: readonly string[]): { status: number; stderr: string; stdout: string } {
  const r = spawnSync("systemctl", ["--user", ...args], {
    encoding: "utf8",
    timeout: 15_000,
  });
  return {
    status: r.status ?? 1,
    stderr: r.stderr ?? "",
    stdout: r.stdout ?? "",
  };
}

export function systemdUnitActive(): boolean {
  const r = userSystemctl(["is-active", "--quiet", UNIT_NAME]);
  return r.status === 0;
}

export function installUserUnit(): void {
  const dir = userSystemdDir();
  mkdirSync(dir, { recursive: true });
  const path = unitPath();
  const { argv, pathEnv } = resolveDaemonArgv();
  const next = renderMbaUserUnit({ execStart: execStartLine(argv), pathEnv });

  const dropIn = localDropInPath();
  if (!existsSync(dropIn) && existsSync(path)) {
    const prev = readFileSync(path, "utf8");
    if (!prev.includes(UNIT_MARKER)) {
      const extra = extraEnvironmentLines(prev);
      if (extra.length > 0) {
        mkdirSync(dirname(dropIn), { recursive: true });
        writeFileSync(dropIn, renderLocalDropIn(extra), "utf8");
      }
    }
  }

  writeFileSync(path, next, "utf8");
  const reload = userSystemctl(["daemon-reload"]);
  if (reload.status !== 0) {
    throw new Error(`systemctl daemon-reload failed: ${reload.stderr.trim() || reload.stdout.trim()}`);
  }
}

export function startUserUnit(): void {
  const r = userSystemctl(["enable", "--now", UNIT_NAME]);
  if (r.status !== 0) {
    throw new Error(`systemctl enable --now ${UNIT_NAME} failed: ${r.stderr.trim() || r.stdout.trim()}`);
  }
  tryLinger();
}

export function stopUserUnit(): void {
  const r = userSystemctl(["stop", UNIT_NAME]);
  if (r.status !== 0) {
    throw new Error(`systemctl stop ${UNIT_NAME} failed: ${r.stderr.trim() || r.stdout.trim()}`);
  }
}

function tryLinger(): void {
  const user = process.env.USER;
  if (!user) return;
  try {
    spawnSync("loginctl", ["enable-linger", user], { encoding: "utf8", timeout: 4000 });
  } catch {
    // Optional: user systemd still runs while logged in.
  }
}

export function spawnDetachedDaemon(): void {
  const { argv, pathEnv } = resolveDaemonArgv();
  const [cmd, ...args] = argv;
  if (!cmd) throw new Error("could not resolve the daemon entry");
  const child = spawn(cmd, args, {
    detached: true,
    stdio: "ignore",
    env: { ...process.env, PATH: pathEnv },
  });
  child.unref();
}
